// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djazugrugnrgbpbpofop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqYXp1Z3J1Z25yZ2JwYnBvZm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNTc1ODcsImV4cCI6MjA3NDgzMzU4N30.27jExOD3sq0j2_AtfUL8kK1z-K-WCEcdwxZ6XsFtyYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});